name: Conditional-Workflow
on: [push]
jobs:
  hello-world:
    if: github.repository == 'YashzAlphaGeek/Spring-Boot-JPA-Hibernate-Query-Methods'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello Spring Boot"
        run:  echo "Hello Spring Boot!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run:  echo "Goodbye Moon!"