name: Conditional-Workflow
on: [push]
jobs:
  hello-world:
    if: github.repository == 'YashzAlphaGeek/Github-Examples-YashzPractice'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello Github-Examples-YashzPractice"
        run:  echo "Hello Github-Examples-YashzPractice!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run:  echo "Goodbye Moon!"