name: "Context Workflow"

on:
  push:
    branches:
      - main

jobs:
  context-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1"
        run: echo "Hello! {github.actor}"
        env:
            MY_ACTION: ${{github.action}}
            MY_ACTOR: ${{github.actor}}