name: "Custom Action Workflow"

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: YashzAlphaGeek/potential-disco@v1.1
        with:
          name: 'Yashwanth'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"